name: Publish Release

on:
  workflow_dispatch:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.101
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish -c Release --no-restore -o ./publish/TerraformProviderRegistry
      
    - name: Archive project
      run: zip -j ./publish/TerraformProviderRegistry.zip ./publish/TerraformProviderRegistry/*

    - uses: ncipollo/release-action@v1
      with:
        artifacts: ./publish/TerraformProviderRegistry.zip
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
